### ISSUE TITLE
Cannot read property 'modules' of undefined

### ISSUE THREAD

**Issue by bhoomit** [pinterest/bonsai#17]
I'm using the following command to generate stats file

`webpack --json --config ./build/webpack.config.js > stats.json`

Getting this error. 

```
getChunkModules.js:25 Uncaught TypeError: Cannot read property 'modules' of undefined
    at getChunkModules.js:25
    at Array.reduce (<anonymous>)
    at o (getChunkModules.js:24)
    at o (fullModuleData.js:50)
    at t.value (Stats.js:41)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    at d._renderValidatedComponent (ReactCompositeComponent.js:822)
    at d._updateRenderedComponent (ReactCompositeComponent.js:746)
    at d._performComponentUpdate (ReactCompositeComponent.js:724)
    at d.updateComponent (ReactCompositeComponent.js:645)
```

I'm using it on https://pinterest.github.io/bonsai/analyze/

**Comment by ryan953** [comment]
@bhoomit It looks like the error is `Cannot read property 'modules' of undefined`. My guess is that the stats file is empty and the JSON.parse call is turning it into undefined. 

Can you verify that `stats.json` is not an empty file, you can also share your webpack.config.js file and I can help figure out what might be going on.

In the mean time I can add a task to my list to more thoroughly check the shape of the stats data before proceeding.

**Comment by boneskull** [comment]
I am experiencing this error as well.  `stats.json` is nonempty.

**Comment by boneskull** [comment]
`stats.json` is also valid:

```shell
$ node
> require('./stats.json') // does not throw
```

**Comment by boneskull** [comment]
This occurs in `master` and on the hosted app.

**Comment by ryan953** [comment]
yeah, so I had some time to look more closely at this, and sure enough at [`getChunkModules.js:25`](https://github.com/pinterest/bonsai/blob/master/src/stats/getChunkModules.js#L25) uses square braces to fetch an item from a map, then tries right away to read a field. This is unsafe and would cause the problem you see. 
So I'm going to make that callsite continue with an empty array or `.modules` so it doesn't bail and try to findout why flow didn't pick it up.

**Comment by bhoomit** [comment]
@ryan953 sure. Thanks a lot. I will try it out. Are you redeploying hosted app? Or I should clone and try it?

**Comment by ryan953** [comment]
Let me know how that's working @bhoomit

Also I'm curious to collect stories of things people have been finding, but if it's sensitive code I understand.

**Comment by bhoomit** [comment]
@ryan953 worked perfectly :) Thanks.

**Comment by boneskull** [comment]
I'm still experiencing this issue against changeset 0cf9efe and the demo site.
