### ISSUE TITLE
stats filed uploaded swallowing errors 

### ISSUE THREAD

**Issue by jamez14** [pinterest/bonsai#19]
During the uploading of a `stats.json` file, any errors that occur are swallowed in the `onStatsFileUploaded` `catch` block. 

The error I received (after putting a breakpoint in the `catch`) is: `"Unexpected number in JSON at position 2"` with a stacktrace of: 

```
"SyntaxError: Unexpected number in JSON at position 2
    at JSON.parse (<anonymous>)
    at n.onStatsFileUploaded (http://localhost:5000/static/js/main.596bcce5.js:3:19672)
    at FileReader.n.onloadend (http://localhost:5000/static/js/main.596bcce5.js:3:16567)"
```

I'd be happy to open up a PR to fix the error swallowing, but would like to hear any thoughts on the best way to notify users of this error. Whether an error shows up in the UI or just a `console` error being thrown.

---

Also, just an FYI, the error was caused because the package `write-file-webpack-plugin` is writing some logging messages that the `stats` file was picking up. In particular, the log messages were:

```
[08:51:58] [write-file-webpack-plugin] options { exitOnErrors: true,
  force: false,
  log: true,
  test: null,
  useHashIndex: true }
[08:52:34] [write-file-webpack-plugin] compiler.outputFileSystem is "NodeOutputFileSystem".
```

but this is not what this issue is about. Just wanted to provide the info to someone else down the line.

**Comment by ryan953** [comment]
Woah, thanks for investigating. Stomping on the errors in onStatsFileUploaded is not good, we should probably at least spew a console.log and then `alert()` so people know what's happened and can step in to see the values. Over time we can iterate and make it better.

I guess there are a lot of plugins like `write-file-webpack-plugin` which could print some extra stuff to the console. It's really going to depend on the contents of that webpack.config.js file, so everyone could have unqiue problems, maybe we could add an editor so you can make valid json and recover from the error?

**Comment by ryan953** [comment]
I'm not a huge bash expert, but do you know if there is a way beyond the redirect operator to capture just the json output and not the logging?

**Comment by jamez14** [comment]
Yeah that would certainly be useful to have a way to quickly edit/validate your json, even just put the contents of the `stats.json` file in a textarea (with line numbers) so users could quickly track down what line number was causing the issue. In my case, it was very apparent that at line 2 there was some invalid json.

Ideally finding a package (or even existing service) that would accept JSON to validate and return the result would be great, even if it redirected the user (if they clicked on a link) so they could quickly trace the error using a third party service.

As far as just capturing the JSON output and not the logging, I'm not personally aware of a way to do that.

**Comment by ryan953** [comment]
I'll write it down later today as a Project because it sounds like there'll be a few more moving parts. 

I hope the diff I just landed helps to get people unstuck in the mean time. I'm sure you're not the only one to have hit this so far.

**Comment by ryan953** [comment]
I'm closing this now because it's been recorded into https://github.com/pinterest/bonsai/projects/3#card-3221121.
Might not even need to have a powerful editor, just auto-format and then rm the extra lines that are bad. I hope this is the same problem that they're having in #17
