### ISSUE TITLE
Add support for multi-config webpack.config.js

### ISSUE THREAD

**Issue by szimek** [pinterest/bonsai#27]
Bonsai currently crashes when [multi-config](https://webpack.js.org/concepts/targets/#multiple-targets) is used. In such case, the generated JSON file has a `children` prop, which is an array of generated targets, i.e. `stats.chunks` doesn't exist, but `stats.children[0].chunks` does. This causes an error in [getEntryHeirarchy.js#L30](https://github.com/pinterest/bonsai/blob/2fcedceedce0d6def166d303e4d05d27f989f868/src/stats/getEntryHeirarchy.js#L30), because `stats.chunks` is `undefined`.

**Comment by ryan953** [comment]
Ah, yeah that'll happen. I'll get in there soon and see what I can do to expose the different children in a readable way.

In the meantime you might be able to workaround this by creating a wrapper js file for the config, and then exporting just one config at a time (just for --json purposes, not for your real build.)

**Comment by szimek** [comment]
That's exactly what I did ;) Thanks!
