### ISSUE TITLE
module name "new RegExp(*)"

### ISSUE THREAD

**Issue by boneskull** [pinterest/bonsai#29]
What does this mean?

![image](https://user-images.githubusercontent.com/924465/26847637-a2b9ab80-4ab2-11e7-8e16-1e0d918f357a.png)

It contains all entry points in the bundle.

**Comment by ryan953** [comment]
Those are filters for the table below. The text represents the current filter values, so you're looking at the regular expression that matches `.*` which is any module name. The other columns are set to be within zero and infinity, so everything is shown in the table. 

You can click those black buttons to get the little input boxes and set the filters. For completeness I'll also point out that the columns are all sortable if you click on the blue titles.

Thanks for asking, this is a good question @boneskull. I feel embarrassed that I didn't already include it in the docs or elsewhere... so I'm really sorry you got tripped up on it. I'll add some docs for the next person, and try to make it more obvious in the UI. I'll try to make them look more like buttons, maybe squeeze a label in there, and add tooltips as in #28 for starters.

**Comment by ryan953** [comment]
Fixed with #33
