### ISSUE TITLE
Add some way of sharing a visualization

### ISSUE THREAD

**Issue by lhorie** [pinterest/bonsai#41]

**Comment by ryan953** [comment]
Hey @lhorie
I've been thinking about this too, and I got a little stuck right now. 
Well, let me first ask, have you set up a server to pick your stats file from? I have on my todo list a task to encode the file & ignored paths in the URL, but I can only make that work if I can fetch the file again and know it's URL. 

Without the server idk... I could setup a public server, but I'd have to save people's data which has some other considerations. Do you have any ideas?

**Comment by lhorie** [comment]
One way would be to have some sort of querystring param `?url=http://something/stats.json` that fetches the file, but admittedly, having to set up a server just for this is a bit of a hassle.

Alternatively, this project could be on npm, and there could be some way of feeding a stats file url directly from CLI. Then, people could just npm install bonsai, and share a CLI command like `bonsai /path/to/stats.json` that would then launch a local server running the web app with the file preloaded.

**Comment by ryan953** [comment]
So we do have something like this. Head over to https://pinterest.github.io/bonsai/build-options.html and checkout the REACT_APP_STATS_URL field. 
You can grab Bonsai from npm with 'npm install bonsai-analyzer' and then set that param and do a build. As long as the file is accessible should be good to go, including using file:// urls and no server. All the usual rules apply with that though.

**Comment by ryan953** [comment]
Closing this out because we've got bookmarkable urls now! It'll only work when a server is setup, but it gets things moving.

You can test it by jumping straight into the first chunk in the example data: https://pinterest.github.io/bonsai/analyze/#filename=%2Fbonsai%2Fexample.json&chunk=0
(might need a reload for the service worker to catch up)
